`<<<<<<< HEAD
name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          ex1:
            - 'src/Exercice1/**'
          ex2:
            - 'src/Exercice2/**'
          ex3:
            - 'src/Exercice3/**'
          ex4:
            - 'src/Exercice4/**'

    - name: Exercice 1
      if: steps.filter.outputs.ex1 == 'true'
      uses: php-actions/phpunit@master
      with:
        testsuite: ex1
        args: --testdox

    - name: Exercice 2
      if: steps.filter.outputs.ex2 == 'true'
      uses: php-actions/phpunit@master
      with:
        testsuite: ex2
        args: --testdox

    - name: Exercice 3
      if: steps.filter.outputs.ex3 == 'true'
      uses: php-actions/phpunit@master
      with:
        testsuite: ex3
        args: --testdox

    - name: Exercice 4
      if: steps.filter.outputs.ex4 == 'true'
      uses: php-actions/phpunit@master
      with:
        testsuite: ex4
        args: --testdox
=======
name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      ex1: ${{ steps.filter.outputs.ex1 }}
      ex2: ${{ steps.filter.outputs.ex2 }}
      ex3: ${{ steps.filter.outputs.ex3 }}
      ex4: ${{ steps.filter.outputs.ex4 }}
      ex5: ${{ steps.filter.outputs.ex5 }}
      ex6: ${{ steps.filter.outputs.ex6 }}
      ex7: ${{ steps.filter.outputs.ex7 }}
<<<<<<< HEAD
=======
      ex8: ${{ steps.filter.outputs.ex8 }}
<<<<<<< HEAD
>>>>>>> upstream/main
=======
      ex9: ${{ steps.filter.outputs.ex9 }}
<<<<<<< HEAD
>>>>>>> upstream/main
=======
      ex10: ${{ steps.filter.outputs.ex10 }}
<<<<<<< HEAD
>>>>>>> upstream/main
=======
      gilded_rose: ${{ steps.filter.outputs.gilded_rose }}
>>>>>>> upstream/main
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          ex1:
            - 'src/Exercice1/**'
          ex2:
            - 'src/Exercice2/**'
          ex3:
            - 'src/Exercice3/**'
          ex4:
            - 'src/Exercice4/**'
          ex5:
            - 'src/Exercice5/**'
          ex6:
            - 'src/Exercice6/**'
          ex7:
            - 'src/Exercice7/**'
<<<<<<< HEAD
=======
          ex8:
            - 'src/Exercice8/**'
<<<<<<< HEAD
>>>>>>> upstream/main
=======
          ex9:
            - 'src/Exercice9/**'
<<<<<<< HEAD
>>>>>>> upstream/main
=======
          ex10:
            - 'src/Exercice10/**'
<<<<<<< HEAD
>>>>>>> upstream/main
=======
          gilded_rose:
            - 'src/TheGildedRose/**'
>>>>>>> upstream/main

  ex1:
    needs: changes
    if: ${{ needs.changes.outputs.ex1 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 1
      id: ex1
      uses: php-actions/phpunit@master
      with:
        testsuite: ex1
        args: --testdox

  ex2:
    needs: changes
    if: ${{ needs.changes.outputs.ex2 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 2
      id: ex2
      uses: php-actions/phpunit@master
      with:
        testsuite: ex2
        args: --testdox

  ex3:
    needs: changes
    if: ${{ needs.changes.outputs.ex3 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 3
      id: ex3
      uses: php-actions/phpunit@master
      with:
        testsuite: ex3
        args: --testdox

  ex4:
    needs: changes
    if: ${{ needs.changes.outputs.ex4 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 4
      id: ex4
      uses: php-actions/phpunit@master
      with:
        testsuite: ex4
        args: --testdox

  ex5:
    needs: changes
    if: ${{ needs.changes.outputs.ex5 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 5
      id: ex5
      uses: php-actions/phpunit@master
      with:
        testsuite: ex5
        args: --testdox

  ex6:
    needs: changes
    if: ${{ needs.changes.outputs.ex6 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 6
      id: ex6
      uses: php-actions/phpunit@master
      with:
        testsuite: ex6
        args: --testdox

  ex7:
    needs: changes
    if: ${{ needs.changes.outputs.ex7 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 7
      id: ex7
      uses: php-actions/phpunit@master
      with:
        testsuite: ex7
        args: --testdox
<<<<<<< HEAD
=======

  ex8:
    needs: changes
    if: ${{ needs.changes.outputs.ex8 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 8
      id: ex8
      uses: php-actions/phpunit@master
      with:
        testsuite: ex8
        args: --testdox
<<<<<<< HEAD
>>>>>>> upstream/main
=======

  ex9:
    needs: changes
    if: ${{ needs.changes.outputs.ex9 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 9
      id: ex9
      uses: php-actions/phpunit@master
      with:
        testsuite: ex9
        args: --testdox
<<<<<<< HEAD
>>>>>>> upstream/main
=======

  ex10:
    needs: changes
    if: ${{ needs.changes.outputs.ex10 == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Exercice 10
      id: ex10
      uses: php-actions/phpunit@master
      with:
        testsuite: ex10
        args: --testdox
<<<<<<< HEAD
>>>>>>> upstream/main
=======

  gilded_rose:
    needs: changes
    if: ${{ needs.changes.outputs.gilded_rose == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: The Gilded Rose
      id: gilded_rose
      uses: php-actions/phpunit@master
      with:
        testsuite: gilded_rose
        args: --testdox
>>>>>>> upstream/main
